### ISSUE TITLE
For `Playground`, please follow the Apache-2 license correctly and remove the statistics code from the code.

### ISSUE THREAD

**Issue by Zxilly** [saki-lang/saki-dev#1]
https://saki-lang.tech/ uses the code from https://github.com/Zxilly/playground-cj. Please follow the Apache-2 license and remove the `umami` trace event from the code.

**Comment by RIvance** [comment]
Thank you for your noticing, and I apologize for any inconvenience. The playground has already been taken down and will be replaced with documentation soon. It was for internal testing only, and the URL hasn't been shared publicly. So I hope it hasn't affected you too much. This is a temporary solution, and the new playground is under redevelopment (without using your code). The playground won't be accessible on the public web until the new one is ready. I appreciate your understanding.

**Comment by Zxilly** [comment]
The main issue is to please remove the tracking code, which is located in src/components/TrackingScript.tsx

**Comment by RIvance** [comment]
I understand your consideration and thanks for your reply. As mentioned above, the playground is now taken down. We will integrate a freshly developed playground into the documents, so the old one, as a temporary solution, is not going to be used anymore. Thus, it won't send you spam tracking data anymore. We also appreciate your project; it is brilliant work and helped us a lot. Thanks for understanding.
